// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GestionEventos.API.Migrations
{
    [DbContext(typeof(AppGestionEventosDbContext))]
    [Migration("20250524023616_PruebaDeDB")]
    partial class PruebaDeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEventos.Modelos.Certificado", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<bool>("AsistenciaCompleta")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("InscripcionCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("PagoRealizado")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("Codigo");

                    b.HasIndex("InscripcionCodigo")
                        .IsUnique();

                    b.ToTable("Certificado");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Evento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Informacion", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int?>("CertificadoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PagoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ParticipanteCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Codigo");

                    b.HasIndex("CertificadoCodigo");

                    b.HasIndex("EventoCodigo");

                    b.HasIndex("PagoCodigo");

                    b.HasIndex("ParticipanteCodigo");

                    b.ToTable("Informaciones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Inscripcion", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ParticipanteCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Codigo");

                    b.HasIndex("EventoCodigo");

                    b.HasIndex("ParticipanteCodigo");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Pago", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("InscripcionCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.HasIndex("InscripcionCodigo")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Participante", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Ponente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.ToTable("Ponentes");
                });

            modelBuilder.Entity("GestionEventos.Modelos.PonenteEvento", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PonenteCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Codigo");

                    b.HasIndex("EventoCodigo");

                    b.HasIndex("PonenteCodigo");

                    b.ToTable("PonenteEventos");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Sesion", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<int>("EventoCodigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Codigo");

                    b.HasIndex("EventoCodigo");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Certificado", b =>
                {
                    b.HasOne("GestionEventos.Modelos.Inscripcion", "Inscripcion")
                        .WithOne("Certificado")
                        .HasForeignKey("GestionEventos.Modelos.Certificado", "InscripcionCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Informacion", b =>
                {
                    b.HasOne("GestionEventos.Modelos.Certificado", "Certificado")
                        .WithMany("Informaciones")
                        .HasForeignKey("CertificadoCodigo");

                    b.HasOne("GestionEventos.Modelos.Evento", "Evento")
                        .WithMany("Informaciones")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEventos.Modelos.Pago", "Pago")
                        .WithMany("Informaciones")
                        .HasForeignKey("PagoCodigo");

                    b.HasOne("GestionEventos.Modelos.Participante", "Participante")
                        .WithMany("Informaciones")
                        .HasForeignKey("ParticipanteCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificado");

                    b.Navigation("Evento");

                    b.Navigation("Pago");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Inscripcion", b =>
                {
                    b.HasOne("GestionEventos.Modelos.Evento", "Evento")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEventos.Modelos.Participante", "Participante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("ParticipanteCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Pago", b =>
                {
                    b.HasOne("GestionEventos.Modelos.Inscripcion", "Inscripcion")
                        .WithOne("Pago")
                        .HasForeignKey("GestionEventos.Modelos.Pago", "InscripcionCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GestionEventos.Modelos.PonenteEvento", b =>
                {
                    b.HasOne("GestionEventos.Modelos.Evento", "Evento")
                        .WithMany("PonenteEventos")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEventos.Modelos.Ponente", "Ponente")
                        .WithMany("PonenteEventos")
                        .HasForeignKey("PonenteCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Ponente");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Sesion", b =>
                {
                    b.HasOne("GestionEventos.Modelos.Evento", "Evento")
                        .WithMany("Sesiones")
                        .HasForeignKey("EventoCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Certificado", b =>
                {
                    b.Navigation("Informaciones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Evento", b =>
                {
                    b.Navigation("Informaciones");

                    b.Navigation("Inscripciones");

                    b.Navigation("PonenteEventos");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Inscripcion", b =>
                {
                    b.Navigation("Certificado");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Pago", b =>
                {
                    b.Navigation("Informaciones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Participante", b =>
                {
                    b.Navigation("Informaciones");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("GestionEventos.Modelos.Ponente", b =>
                {
                    b.Navigation("PonenteEventos");
                });
#pragma warning restore 612, 618
        }
    }
}
